### ISSUE TITLE
Unicode "font" titles for comments?

### ISSUE THREAD

**Issue by thedonquixotic** [brunnerh/insert-unicode#1]
Hey I know this might be beyond the scope of what you're trying to do, but it would be cool if you could add the ability to convert text to unicode "fonts" like this: https://lingojam.com/FancyTextGenerator

It's generally useful for small comments that still need to be easy to see. 

I use this extension for making large ASCI banner comments and it's workflow with the command palette is not very far off from yours. https://github.com/vanessa-luna/banner-comments-plus

**Comment by brunnerh** [comment]
I have actually written a user script that does such conversions about a month ago. If i find the time i might integrate that as a separate command.

**Comment by thedonquixotic** [comment]
@brunnerh   RAD!  (also I'm very new to coding so I don't know how to use user scripts in vscode exactly but if you link me it I'd love to take a shot at using it. I'm also kind of curious how I can start extending VScode myself. I've been doing a lot of weird hacky stuff using a custom CSS and JS injector but there's def more I could do :)  )

**Comment by thedonquixotic** [comment]
👍 rad thanks for explaining!

**Comment by brunnerh** [comment]
Some font conversions should now be available, though not all of them work (4bde53db7764ea7f9796cd1899dd47c11cc7f156).

**Comment by thedonquixotic** [comment]
NICE! It works perfectly! Thank you!
