### ISSUE TITLE
Inserting combining macrons

### ISSUE THREAD

**Issue by paradoXp** [brunnerh/insert-unicode#10]
I would like to add macrons to letters e.g. add `U+0304` to `U+0054` result `X̄`. As I understand it the `U+0304` macron can be added to any character, but I can't figure out how to do it using the extension.

**Comment by brunnerh** [comment]
@paradoXp First, type the letter, then execute the `Insert Unicode` command and search for `macron` (if you have pre-filtering enabled, you have to hit enter one more time to get the list containing the character):

![image](https://user-images.githubusercontent.com/834235/65275129-4508fa80-db25-11e9-9991-16614d77aff0.png)

When you hit enter it should be applied to the letter.

![image](https://user-images.githubusercontent.com/834235/65275166-594cf780-db25-11e9-910a-0185cc604555.png)

(As you already know the code, you can also execute the command `Insert Unicode from Hex Code`, type `304` and hit enter to apply the character.)

**Comment by paradoXp** [comment]
Well, that was easy...I must have tried every other combination, but not the simple one 🙂. Thanks!
