### ISSUE TITLE
Math Bold for numbers it doesn't work

### ISSUE THREAD

**Issue by LeninZapata** [brunnerh/insert-unicode#11]
Hello, when I want to transform the text in **Math Bold** into letters it works fine, but in number it does not convert them, this is a page [Yaytext](https://yaytext.com/bold-italic/) where I transform it and it works for number and letter, could you correct this?
![image](https://user-images.githubusercontent.com/42600954/69556355-91801480-0f72-11ea-9ca4-7bc79209343d.png)

**Comment by brunnerh** [comment]
Should not be too difficult, but i cannot make any promises about when i will get around to it.

**Comment by LeninZapata** [comment]
Ok, I hope you can take it back soon thank you very much.
