### ISSUE TITLE
Results not showing up

### ISSUE THREAD

**Issue by brunnerh** [brunnerh/insert-unicode#12]
From issue #9 

> I'm with David263. I don't get it.
> 
> 1. Select Insert option
>    ![image](https://user-images.githubusercontent.com/1784452/70457322-90bca780-1a75-11ea-8a3f-fca1426a5161.png)
> 2. Get prompt
>    ![image](https://user-images.githubusercontent.com/1784452/70457268-784c8d00-1a75-11ea-93cd-b0f9489ce065.png)
> 3. Enter example text and there are no search results
>    ![image](https://user-images.githubusercontent.com/1784452/70457755-556ea880-1a76-11ea-8e81-b9935ab12d60.png)
> 4. Press Enter and there are no search results
>    ![image](https://user-images.githubusercontent.com/1784452/70457841-7df6a280-1a76-11ea-919b-afd068368bd2.png)
> 5. Type something else and there are still no search results
>    ![image](https://user-images.githubusercontent.com/1784452/70458037-e47bc080-1a76-11ea-9770-76010b384765.png)
> 
> I can't get the extension to do anything!

The prompt shows `(7)` results but nothing is visible. Also, it only should show `(2)`:

![image](https://user-images.githubusercontent.com/834235/70459615-d8165880-1ab4-11ea-9287-774b61705ba5.png)

**Comment by brunnerh** [comment]
@MisinformedDNA

1. What version of VS Code?
2. What version of the extension?
3. What settings are set for the extension?

**Comment by MisinformedDNA** [comment]
I upgraded VS Code and everything works now. Sorry for the trouble. I updated my rating/review on the Marketplace.
