### ISSUE TITLE
unicode favorites not stored

### ISSUE THREAD

**Issue by rzw** [brunnerh/insert-unicode#18]
The unicode favorites aren't stored. If I have two identically named folders at the same level, the program correctly displays an error message upon saving. So the saving routine does something.

But generally: I save, close, reopen "manage favorites" and all is gone. I downloded the vs code zip and work with the non-installed version of vs code.

**Comment by brunnerh** [comment]
Maybe related to #16. Will look into it when i have some time.

**Comment by brunnerh** [comment]
@rzw Can you get v.0.9.0 and check what happens there?

**Comment by brunnerh** [comment]
Closing for now due to inactivity.
If the problem can be reproduced in the most current version, feel free to reopen.
