### ISSUE TITLE
Be lenient on known anomalies UTN#27

### ISSUE THREAD

**Issue by smasher164** [brunnerh/insert-unicode#19]
There's a finite list of anomalies in Unicode character names. For example, **_lambda_** is spelled incorrectly as **_lamda_** for U+039B and U+03BB. This list is documented in UTN#27: https://unicode.org/notes/tn27/. Is it possible to extend the normal search (not exact) to take these into account?

**Comment by brunnerh** [comment]
@smasher164 Not all of these are particularly clear on how one would go about rectifying the situation. Do you personally just want lambda fixed?

It probably would be possible to add an additional string somewhere in the item dropdown so it is found.

**Comment by smasher164** [comment]
Most of the spelling errors on that site have formal aliases already defined, so the only things that need to be fixed are 
```
U+039B GREEK CAPITAL LETTER LAMDA
U+03BB GREEK SMALL LETTER LAMDA

The use of the spelling lamda derives from ISO 10646.
This does not mean that it is more correct than lambda,
merely that the spelling without the 'b' is the one used in
the formal character names.

U+0A01 GURMUKHI SIGN ADAK BINDI

The spelling of the word Adak with a single 'd' is inconsistent
with U+0A71 GURMUKHI ADDAK and should really have had two d's.
```

So, I propose the following aliases be added:

Alias | Actual
------------ | -------------
U+039B GREEK CAPITAL LETTER LAMBDA | U+039B GREEK CAPITAL LETTER LAMDA
U+03BB GREEK SMALL LETTER LAMBDA | U+03BB GREEK SMALL LETTER LAMDA
U+0A01 GURMUKHI SIGN ADDAK BINDI|U+0A01 GURMUKHI SIGN ADAK BINDI
