### ISSUE TITLE
Insert Unicode (Hex Code) doesn't work

### ISSUE THREAD

**Issue by tklink** [brunnerh/insert-unicode#2]
Ctrl-Shift-P, Insert Unicode (Hex Code), type "2212" expecting to find the "minus" character but nothing is found instead saying "No items found for 2212".

**Comment by brunnerh** [comment]
The pre-filtering search currently only searches the name of the code point. This command would insert the text `0x2212` instead of `−`, so there is little point in using it if you already know the hex code. Did you expect the command to insert `−` but search by code?

**Comment by tklink** [comment]
The *Insert Unicode* plugin is described as *Search for unicode characters and insert them into documents*. So I expect it to always insert a *unicode character* (such as `−`), not the entered string (such as `0x2212`). Moreover, when a command name says *Insert Unicode (Hex Code)*, nothing warns me that it looks for hex codes only in character names. Instead, I expect that *hex code* is to be entered regardless of the character name.

**Comment by brunnerh** [comment]
You misunderstood the intent then. For inserting Unicode characters by hex code [there already is support in most operating systems](https://en.wikipedia.org/wiki/Unicode_input), so the prime use case of this extension is to make it easier to get from a more easily remembered name to the character or its hex representation (which may be required as an escape in some programming languages).

If you want to search by hex code you can disable the initial search via the setting `insert-unicode.disable-pre-filtering` as a workaround; this will have a performance impact though. I am reluctant to implement any changes as this apparently is a very rare use case.

**Comment by tklink** [comment]
I can use operating system support for entering unicode characters on Linux (Ctrl-Shift-U…) without problems. Unfortunately the same method on Windows (Altr-NumPlus-…) often fails in Visual Studio Code because of conflict with hotkeys or menu items. Therefore I hoped this plugin can provide a reliable way to enter unicode characters by name (actually a very good service) and also by its code to overcome such conflicts. If it is not this case, I accept it. I am only persuaded that the command name "Insert Unicode (Hex Code)" is misleading in this case.

**Comment by brunnerh** [comment]
(Will publish to marketplace later today.)
