### ISSUE TITLE
ENAMETOOLONG error on install on linux

### ISSUE THREAD

**Issue by viell-dev** [brunnerh/insert-unicode#26]
Visual Studio Code (tested on 1.57.0) fails to install 0.12.0 on linux (mint in my case) with node error `ENAMETOOLONG`.
```bash
[2021-06-14 09:32:30.045] [renderer1] [error] ["extracting: ENAMETOOLONG: name too long, open '/home/viell/.vscode/extensions/.9e115ead-e803-4b12-854f-45b916de8551/out/commands/node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_revogr-clip-fe8f0a.node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_revogr-clip-fe8f0a.js'","    at l.extractAtLocation (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:183960)","    at async l.extractUserExtension (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:180962)","    at async G.extractAndInstall (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:198663)","    at async G.doInstallFromGallery (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:195230)"]
[2021-06-14 09:32:30.131] [renderer1] [error] ENAMETOOLONG: name too long, open '/home/viell/.vscode/extensions/.9e115ead-e803-4b12-854f-45b916de8551/out/commands/node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_revogr-clip-fe8f0a.node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_revogr-clip-fe8f0a.js': extracting: ENAMETOOLONG: name too long, open '/home/viell/.vscode/extensions/.9e115ead-e803-4b12-854f-45b916de8551/out/commands/node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_revogr-clip-fe8f0a.node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_revogr-clip-fe8f0a.js'
    at l.extractAtLocation (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:183960)
    at async l.extractUserExtension (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:180962)
    at async G.extractAndInstall (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:198663)
    at async G.doInstallFromGallery (file:///usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:54:195230)
```

I tried unzipping the `.vsix` file in order to install the extention manually.
These are the files that have too long names:
```
extension/out/commands/node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_revogr-clip-fe8f0a.node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_revogr-clip-fe8f0a.js
extension/out/commands/vendors-node_modules_revolist_revogrid_dist_esm-es5_css-shim-934c915f_js.vendors-node_modules_revolist_revogrid_dist_esm-es5_css-shim-934c915f_js.js
extension/out/commands/vendors-node_modules_revolist_revogrid_dist_esm-es5_resize-observer-56b7b34f_js.vendors-node_modules_revolist_revogrid_dist_esm-es5_resize-observer-56b7b34f_js.js
extension/out/commands/vendors-node_modules_revolist_revogrid_dist_esm-es5_revo-grid_10_entry_js.vendors-node_modules_revolist_revogrid_dist_esm-es5_revo-grid_10_entry_js.js
extension/out/commands/vendors-node_modules_revolist_revogrid_dist_esm-es5_revogr-filter-panel_entry_js.vendors-node_modules_revolist_revogrid_dist_esm-es5_revogr-filter-panel_entry_js.js
extension/out/commands/vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_css-9b0aeb.vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_css-9b0aeb.js
extension/out/commands/vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_res-0513ce.vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_res-0513ce.js
extension/out/commands/vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_rev-39b370.vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_rev-39b370.js
extension/out/commands/vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_rev-ca335a.vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_rev-ca335a.js
```

<details>
  <summary>Output of unzip command.</summary>
<pre>
viell@viell-dev:~/Downloads$ unzip brunnerh.insert-unicode-0.12.0.vsix
Archive:  brunnerh.insert-unicode-0.12.0.vsix
  inflating: extension.vsixmanifest  
  inflating: [Content_Types].xml     
  inflating: extension/.github/ISSUE_TEMPLATE/bug_report.md  
  inflating: extension/CHANGELOG.md  
  inflating: extension/icon/icon.png  
  inflating: extension/icon/icon.svg  
  inflating: extension/icon/identify-view.svg  
  inflating: extension/icon/render.sh  
  inflating: extension/LICENSE.txt   
  inflating: extension/out/commands/150.150.js  
  inflating: extension/out/commands/223.223.js  
  inflating: extension/out/commands/279.279.js  
  inflating: extension/out/commands/32.32.js  
  inflating: extension/out/commands/407.407.js  
  inflating: extension/out/commands/553.553.js  
  inflating: extension/out/commands/729.729.js  
  inflating: extension/out/commands/893.893.js  
  inflating: extension/out/commands/91.91.js  
  inflating: extension/out/commands/938.938.js  
  inflating: extension/out/commands/command-callback.js  
  inflating: extension/out/commands/data-table/data-table-back-end-message.js  
  inflating: extension/out/commands/data-table/data-table-view-message.js  
  inflating: extension/out/commands/data-table/data-table.js  
  inflating: extension/out/commands/data-table/favorites-back-end-message.js  
  inflating: extension/out/commands/data-table/favorites-view-message.js  
  inflating: extension/out/commands/data-table/index.js  
  inflating: extension/out/commands/data-table/manage-favorites.js  
  inflating: extension/out/commands/data-table/utility/message-bus.js  
  inflating: extension/out/commands/data-table/utility/unicode-data.js  
  inflating: extension/out/commands/data-table/view.js  
  inflating: extension/out/commands/hex-to-text.js  
  inflating: extension/out/commands/identify-characters.js  
  inflating: extension/out/commands/insert-character.js  
  inflating: extension/out/commands/insert-favorite.js  
  inflating: extension/out/commands/insert-font.js  
  inflating: extension/out/commands/manage-favorites/favorites-back-end-message.js  
  inflating: extension/out/commands/manage-favorites/favorites-section-type.js  
  inflating: extension/out/commands/manage-favorites/favorites-view-message.js  
  inflating: extension/out/commands/manage-favorites/icons/index.js  
  inflating: extension/out/commands/manage-favorites/index.js  
  inflating: extension/out/commands/manage-favorites/manage-favorites.js  
  inflating: extension/out/commands/manage-favorites/utility/constants.js  
  inflating: extension/out/commands/manage-favorites/utility/favorites-transform.js  
  inflating: extension/out/commands/manage-favorites/utility/message-bus.js  
  inflating: extension/out/commands/manage-favorites/utility/types.js  
  inflating: extension/out/commands/manage-favorites/utility/unicode-data.js  
  inflating: extension/out/commands/manage-favorites/utility/vscode-api.js  
  inflating: extension/out/commands/manage-favorites/view.js  
  inflating: extension/out/commands/node_modules_revolist_revogrid_dist_esm-es5_revogr-clipboard_entry_js.node_modules_revolist_revogrid_dist_esm-es5_revogr-clipboard_entry_js.js  
error:  cannot create extension/out/commands/node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_revogr-clip-fe8f0a.node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_revogr-clip-fe8f0a.js
        File name too long
  inflating: extension/out/commands/polyfills-core-js.polyfills-core-js.js  
  inflating: extension/out/commands/polyfills-dom.polyfills-dom.js  
  inflating: extension/out/commands/recently-used.js  
  inflating: extension/out/commands/svelte/utility/dialog-utility.js  
  inflating: extension/out/commands/svelte/utility/message-bus.js  
  inflating: extension/out/commands/svelte/utility/recently-used-list.js  
  inflating: extension/out/commands/svelte/utility/vscode-api.js  
  inflating: extension/out/commands/svelte/webpack.config.js  
error:  cannot create extension/out/commands/vendors-node_modules_revolist_revogrid_dist_esm-es5_css-shim-934c915f_js.vendors-node_modules_revolist_revogrid_dist_esm-es5_css-shim-934c915f_js.js
        File name too long
error:  cannot create extension/out/commands/vendors-node_modules_revolist_revogrid_dist_esm-es5_resize-observer-56b7b34f_js.vendors-node_modules_revolist_revogrid_dist_esm-es5_resize-observer-56b7b34f_js.js
        File name too long
error:  cannot create extension/out/commands/vendors-node_modules_revolist_revogrid_dist_esm-es5_revo-grid_10_entry_js.vendors-node_modules_revolist_revogrid_dist_esm-es5_revo-grid_10_entry_js.js
        File name too long
error:  cannot create extension/out/commands/vendors-node_modules_revolist_revogrid_dist_esm-es5_revogr-filter-panel_entry_js.vendors-node_modules_revolist_revogrid_dist_esm-es5_revogr-filter-panel_entry_js.js
        File name too long
error:  cannot create extension/out/commands/vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_css-9b0aeb.vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_css-9b0aeb.js
        File name too long
error:  cannot create extension/out/commands/vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_res-0513ce.vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_res-0513ce.js
        File name too long
error:  cannot create extension/out/commands/vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_rev-39b370.vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_rev-39b370.js
        File name too long
error:  cannot create extension/out/commands/vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_rev-ca335a.vendors-node_modules_revolist_svelte-datagrid_node_modules_revolist_revogrid_dist_esm-es5_rev-ca335a.js
        File name too long
  inflating: extension/out/config-interface.js  
  inflating: extension/out/config.js  
  inflating: extension/out/context.js  
  inflating: extension/out/data.js   
  inflating: extension/out/extension.js  
  inflating: extension/out/migrations.js  
  inflating: extension/out/state.js  
  inflating: extension/out/utility/code-conversion.js  
  inflating: extension/out/utility/code-operations.js  
  inflating: extension/out/utility/editor.js  
  inflating: extension/out/utility/favorites.js  
  inflating: extension/out/utility/files.js  
  inflating: extension/out/utility/issues.js  
  inflating: extension/out/utility/messages.js  
  inflating: extension/out/utility/promises.js  
  inflating: extension/out/utility/quick-pick.js  
  inflating: extension/out/utility/recently-used-list.js  
  inflating: extension/out/utility/recently-used-list.json  
  inflating: extension/out/views/identify-view/identify-view.js  
  inflating: extension/package.json  
  inflating: extension/readme-files/data-table.png  
  inflating: extension/readme-files/favorites-manager.png  
  inflating: extension/readme-files/favorites.png  
  inflating: extension/readme-files/font-prompt.png  
  inflating: extension/readme-files/identify-view.png  
  inflating: extension/readme-files/search-prompt.gif
  inflating: extension/README.md
</pre>
</details>

**Comment by brunnerh** [comment]
@viell-dev Should now hopefully work with the latest version.
