### ISSUE TITLE
[Bug] "Math Italic" of "Insert Unicode: Insert/Replace Text with 'Unicode Font'"

### ISSUE THREAD

**Issue by OntoDomina** [brunnerh/insert-unicode#27]
**Describe the bug**
The buggy Command is "Insert Unicode: Insert/Replace Text with "Unicode Font", of which "Math Italic". If apply the command to the letter h, the result would be as the 2nd line in example.

**Example**
```
python
𝑝𝑦𝑡𝑕𝑜𝑛  0x1d455
𝑝𝑦𝑡ℎ𝑜𝑛     0x210e
```

**Possible Cause**
Unicode U+1d455 is reserved because italic h already exist as Planck Constant at U+210E

**Comment by brunnerh** [comment]
You are correct. There are other holes as well, e.g. ℂ is not in the double struck block, because it was already defined before.

I should check all the blocks for such holes and fix them.
