### ISSUE TITLE
The Identify sidebar is blank when theme is dark.

### ISSUE THREAD

**Issue by gmccullo** [brunnerh/insert-unicode#34]
The table is there but the text is black on black.

What it looks like:

![image](https://user-images.githubusercontent.com/26315643/149896454-1f1158bf-8df7-4c28-8700-62b884d4e411.png)

With text selected:

![image](https://user-images.githubusercontent.com/26315643/149896348-d00bdac4-0098-44eb-aef6-d2f6bbf1cafc.png)

**Comment by brunnerh** [comment]
I am always on a dark theme and never had this issue.
![image](https://user-images.githubusercontent.com/834235/149909883-3137eea7-f46a-46c6-a088-5ff7333363bb.png)

Can you try other dark themes and provide more information like VS Code version, extension version and theme name (if from an extension, the ID of that as well)?

**Comment by gmccullo** [comment]
I think I found the problem. I have this in my workbench.colorCustomizations settings:

```json
        "sideBar.background": "#191919",
        "sideBar.foreground": "#aaa",
```

It looks like the sideBar.foreground setting is ignored.
