### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by noraj** [brunnerh/insert-unicode#35]
Hi can you push your extension to https://open-vsx.org/ in addition to VSCode Market Place so people using the FLOSS version could install it too?

I wrote [an article](https://blog.raw.pm/en/FLOSS-version-of-vscode-and-extensions-gallery/) on the subject.

Example of Github Action: https://github.com/HaaLeo/publish-vscode-extension

**Comment by TheDiveO** [comment]
This would also benefit us users of the VSCode server(s), such as [code-server](https://github.com/coder/code-server): this allows VSCode be used from a web browser, including an Android or iOS tablet. One use case is a self-hosted VSCode server on localhost, such as a headless Raspberry Pi (4B/8G is a treat), and then accessing it from the tablet via an SSH tunnel with port forwarding.

**Comment by brunnerh** [comment]
Waiting for https://github.com/EclipseFdn/open-vsx.org/issues/913 ...

**Comment by brunnerh** [comment]
The latest versions of my extensions are now published on Open VSX.
https://open-vsx.org/extension/brunnerh/insert-unicode
