### ISSUE TITLE
Insert CR results in LF

### ISSUE THREAD

**Issue by mat-m** [brunnerh/insert-unicode#36]
**Describe the bug**
When I try to insert a CR (\x0D) character, I finally get a LF \x0A character in the file.

**To Reproduce**
Steps to reproduce the behavior, e.g.
1. Open an editor with CRLF EOL.
2. Call command 'Insert'
3. Select option 'CR'
4. Save the file
5. Open in hex editor (e.g. ms-vscode.hexeditor)

**Expected behavior**

You should have a CR character in the file

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]: Windows 10
 - Visual Studio Code Version: [e.g. 1.40.2 (see Help > About)]  Version: 1.65.2 (user setup)
 - Extension Version [e.g. 0.7.0 (seen next to extension name)]  v0.13.3

**Extension Settings**
Please copy the JSON of all settings you configured for the extension.
None

**Comment by brunnerh** [comment]
That is a normalization that is performed by VS Code itself. If you really care about this, you should open an issue there to suggest that an option be added to disable this. (CR without anything else should not happen in digital documents.)

You can manually edit the file in a hex editor to only insert the CR, but once you open and save it via the text editor this CR will either be turned into LF or CRLF, depending on the current end of line setting.
