### ISSUE TITLE
How to use this extension?

### ISSUE THREAD

**Issue by IsaacHub** [brunnerh/insert-unicode#6]
I have installed this extension, now what? your animated gif shows how to insert a unicode(fire), but how can I get the autocomplete? I pressed <kbd>Ctrl+E</kbd> and typed fire, copyright, etc.. nothing shows up.. Do I have to configure anything?

**Comment by brunnerh** [comment]
@IsaacHub Press enter to trigger the pre-filtering and get the list of unicode characters containing the search string.  I recommend setting the option `insert-unicode.disable-pre-filtering` to `true` to filter the whole unicode list on the fly. (This will be the default soon.)

**Comment by brunnerh** [comment]
Closed for now due to inactivity.
