### ISSUE TITLE
endash

### ISSUE THREAD

**Issue by BobFrankston** [brunnerh/insert-unicode#8]
I appreciate the value in entering emojis but it would be nice to able to insert more mundane characters like endash and 0x2013.

**Comment by brunnerh** [comment]
That is already possible. The official name is 'en dash' so if you search for that you will find it.
Also, if you know the code you can use the command `Insert Unicode from Hex Code` (you have to enter the hex value without the `0x` prefix).

**Comment by BobFrankston** [comment]
Thanks! 

I also searched for "dash" - perhaps it should show partial matches

As to hex, still confused
![image](https://user-images.githubusercontent.com/5490484/63659379-21999c80-c77f-11e9-9946-ffccad8e7bf0.png)

**Comment by brunnerh** [comment]
For the hex that is not the correct command, the command should show up as stated above.

![image](https://user-images.githubusercontent.com/834235/63661855-7c051e00-c7bc-11e9-8300-932a36a4280f.png)

There is no search prompt, it looks like this instead:

![image](https://user-images.githubusercontent.com/834235/63661887-8fb08480-c7bc-11e9-8c9e-e4bf698a4a76.png)

---

These are the results i get for `dash` using the `Insert Unicode` command:

![image](https://user-images.githubusercontent.com/834235/63661795-48c28f00-c7bc-11e9-960f-561c7d1b400a.png)

**Comment by BobFrankston** [comment]
Thanks.

Sorry for my confusion. VC showed the other options much further down so I didn't realize they were there.

**Comment by BobFrankston** [comment]
I do want to thank you for a great utility.
